<a href="https://colab.research.google.com/github/lmcanavals/ml/blob/main/representaciones_de_texto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TF-IDF

## Corpus

In [1]:
%%file corpus.txt
saludo al sol con una sonrisa
cuando sonries se te ven los dientes
como los dientes de un sol de caricatura

Writing corpus.txt


In [12]:
import numpy as np
import pandas as pd

from nltk.tokenize import WhitespaceTokenizer
from nltk.tokenize import RegexpTokenizer
import re

# Reoresentación binaria

In [11]:
with open("corpus.txt") as f:
    corpus = f.readlines()
temp = []
for line in corpus:
    temp.append(line.split())
corpus = temp

print(corpus)

[['saludo', 'al', 'sol', 'con', 'una', 'sonrisa'], ['cuando', 'sonries', 'se', 'te', 'ven', 'los', 'dientes'], ['como', 'los', 'dientes', 'de', 'un', 'sol', 'de', 'caricatura']]


In [12]:
wordsidx = []
for line in corpus:
    wordsidx.extend(line)

wordsidx = list(set(wordsidx))
print(wordsidx)
print(len(wordsidx))
words = {word: idx for idx, word in enumerate(wordsidx)}
print(words)

['se', 'saludo', 'cuando', 'una', 'te', 'ven', 'dientes', 'de', 'los', 'caricatura', 'con', 'al', 'como', 'sol', 'sonrisa', 'un', 'sonries']
17
{'se': 0, 'saludo': 1, 'cuando': 2, 'una': 3, 'te': 4, 'ven': 5, 'dientes': 6, 'de': 7, 'los': 8, 'caricatura': 9, 'con': 10, 'al': 11, 'como': 12, 'sol': 13, 'sonrisa': 14, 'un': 15, 'sonries': 16}


In [13]:
cols, rows = len(wordsidx), len(corpus)
dataset = np.zeros((rows, cols), dtype=int)
for i, line in enumerate(corpus):
    for word in line:
        dataset[i, words[word]] = 1

print(dataset)

[[0 1 0 1 0 0 0 0 0 0 1 1 0 1 1 0 0]
 [1 0 1 0 1 1 1 0 1 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 1 1 1 0 0 1 1 0 1 0]]


### Some real data

In [4]:
url="https://raw.githubusercontent.com/lmcanavals/ml/main/data/spam.csv"
spamdf = pd.read_csv(url,encoding ='latin1')
spamdf.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [6]:
sentence = spamdf["v2"][0]
print(sentence)

Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...


In [8]:
token = WhitespaceTokenizer().tokenize(sentence)
print(token)
print(sentence.split())

['Go', 'until', 'jurong', 'point,', 'crazy..', 'Available', 'only', 'in', 'bugis', 'n', 'great', 'world', 'la', 'e', 'buffet...', 'Cine', 'there', 'got', 'amore', 'wat...']
['Go', 'until', 'jurong', 'point,', 'crazy..', 'Available', 'only', 'in', 'bugis', 'n', 'great', 'world', 'la', 'e', 'buffet...', 'Cine', 'there', 'got', 'amore', 'wat...']


In [9]:
%timeit WhitespaceTokenizer().tokenize(sentence)

7.29 µs ± 728 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [10]:
%timeit sentence.split()

526 ns ± 11.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [13]:
wordsRE = '[a-zA-Z]+'
tokenizer = RegexpTokenizer(wordsRE)
tokens = tokenizer.tokenize(sentence)
print(tokens)

['Go', 'until', 'jurong', 'point', 'crazy', 'Available', 'only', 'in', 'bugis', 'n', 'great', 'world', 'la', 'e', 'buffet', 'Cine', 'there', 'got', 'amore', 'wat']
