<a href="https://colab.research.google.com/github/lmcanavals/ml/blob/main/representaciones_de_texto_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Representaciones basadas en frencuencia

In [28]:
import pandas as pd
import numpy as np
import math
from nltk.tokenize import RegexpTokenizer
import re

In [2]:
url="https://raw.githubusercontent.com/lmcanavals/ml/main/data/spam.csv"
spamdf = pd.read_csv(url,encoding ='latin1')
spamdf.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [3]:
corpus = " ".join(spamdf["v2"].array)
print(corpus[:100])

Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got a


In [4]:
tokenizer = RegexpTokenizer(r'\w+')
tokens = tokenizer.tokenize(corpus)
print(tokens[:20])
print(len(tokens))

['Go', 'until', 'jurong', 'point', 'crazy', 'Available', 'only', 'in', 'bugis', 'n', 'great', 'world', 'la', 'e', 'buffet', 'Cine', 'there', 'got', 'amore', 'wat']
90106


In [5]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [6]:
print(stopwords.words('english'))

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [7]:
print(stopwords.words('spanish'))

['de', 'la', 'que', 'el', 'en', 'y', 'a', 'los', 'del', 'se', 'las', 'por', 'un', 'para', 'con', 'no', 'una', 'su', 'al', 'lo', 'como', 'más', 'pero', 'sus', 'le', 'ya', 'o', 'este', 'sí', 'porque', 'esta', 'entre', 'cuando', 'muy', 'sin', 'sobre', 'también', 'me', 'hasta', 'hay', 'donde', 'quien', 'desde', 'todo', 'nos', 'durante', 'todos', 'uno', 'les', 'ni', 'contra', 'otros', 'ese', 'eso', 'ante', 'ellos', 'e', 'esto', 'mí', 'antes', 'algunos', 'qué', 'unos', 'yo', 'otro', 'otras', 'otra', 'él', 'tanto', 'esa', 'estos', 'mucho', 'quienes', 'nada', 'muchos', 'cual', 'poco', 'ella', 'estar', 'estas', 'algunas', 'algo', 'nosotros', 'mi', 'mis', 'tú', 'te', 'ti', 'tu', 'tus', 'ellas', 'nosotras', 'vosotros', 'vosotras', 'os', 'mío', 'mía', 'míos', 'mías', 'tuyo', 'tuya', 'tuyos', 'tuyas', 'suyo', 'suya', 'suyos', 'suyas', 'nuestro', 'nuestra', 'nuestros', 'nuestras', 'vuestro', 'vuestra', 'vuestros', 'vuestras', 'esos', 'esas', 'estoy', 'estás', 'está', 'estamos', 'estáis', 'están', 'e

In [8]:
from nltk.stem.lancaster import LancasterStemmer

stemmer = LancasterStemmer()

In [9]:
sw = stopwords.words('english')
tokens = [stemmer.stem(w) for w in tokens if not w.lower() in sw]
print(tokens[:20])
print(len(tokens))

['go', 'jurong', 'point', 'crazy', 'avail', 'bug', 'n', 'gre', 'world', 'la', 'e', 'buffet', 'cin', 'got', 'am', 'wat', 'ok', 'lar', 'jok', 'wif']
53415


In [10]:
count = dict()
for token in tokens:
    if not token in count:
        count[token] = 0

    count[token] += 1

In [11]:
len(count)

6614

In [12]:
count['crazy']

15

## Term Frenquency (TF)

$$
tf(t,d)=\frac{ f_{t,d} }{ \sum_{t'\in d}{f_{t',d}} }
$$

## Inverse Document Frequency (IDF)

$$
Idf(t,D)=log\frac{ N }{ |\{d\in D: t \in d\}| }
$$


$N$: Número total de documentos, $N = |D|$

$D$: Todos los documentos

$|\{d\in D: t \in d\}|$: Número de documentos $d$ donde aparece el térmitno $t$

## TF-IDF

$$
tfidf(t, d, D) = tf(t, d) \cdot idf(t, D)
$$

In [14]:
m = len(spamdf)
n = len(count)
X = np.zeros((m, n))
Y = spamdf['v1'].array
print(X.shape)
print(Y.shape)

(5572, 6614)
(5572,)


In [19]:
word2idx = {word: i for i, word in enumerate(count.keys())}

{'go': 0, 'jurong': 1, 'point': 2, 'crazy': 3, 'avail': 4, 'bug': 5, 'n': 6, 'gre': 7, 'world': 8, 'la': 9, 'e': 10, 'buffet': 11, 'cin': 12, 'got': 13, 'am': 14, 'wat': 15, 'ok': 16, 'lar': 17, 'jok': 18, 'wif': 19, 'u': 20, 'on': 21, 'fre': 22, 'entry': 23, '2': 24, 'wkly': 25, 'comp': 26, 'win': 27, 'fa': 28, 'cup': 29, 'fin': 30, 'tkts': 31, '21st': 32, 'may': 33, '2005': 34, 'text': 35, '87121': 36, 'receiv': 37, 'quest': 38, 'std': 39, 'txt': 40, 'rat': 41, 'c': 42, 'apply': 43, '08452810075over18': 44, 'dun': 45, 'say': 46, 'ear': 47, 'hor': 48, 'already': 49, 'nah': 50, 'think': 51, 'goe': 52, 'usf': 53, 'liv': 54, 'around': 55, 'though': 56, 'freemsg': 57, 'hey': 58, 'darl': 59, '3': 60, 'week': 61, 'word': 62, 'back': 63, 'lik': 64, 'fun': 65, 'stil': 66, 'tb': 67, 'xxx': 68, 'chgs': 69, 'send': 70, 'å': 71, '1': 72, '50': 73, 'rcv': 74, 'ev': 75, 'broth': 76, 'speak': 77, 'tre': 78, 'aid': 79, 'pat': 80, 'per': 81, 'request': 82, 'mel': 83, 'oru': 84, 'minnaminungint': 85, '

In [27]:
i = 0
tokenizer = RegexpTokenizer(r'\w+')

N = len(spamdf)

for spam in spamdf['v2']:
    tokens = tokenizer.tokenize(spam)
    tokens = [stemmer.stem(w) for w in tokens if not w.lower() in sw]
    unique = set(tokens)
    for word in unique:
        widx = word2idx[word]
        tf = spam.count(word) / len(unique)
        X[i][widx] = tf

    i += 1

# Falta el IDF...

    i += 1

print(X[1000:1010, 1000:1010])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### SKLearn vectorization

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [38]:
tokenizer = RegexpTokenizer(r'[a-zA-Z]+')
vectorizer = TfidfVectorizer(stop_words=stopwords.words('english'),
                             tokenizer=tokenizer.tokenize)
X = vectorizer.fit_transform(spamdf['v2'].array)
tokens = vectorizer.get_feature_names_out()
print(X.shape)
print(tokens[:10])

(5572, 7564)
['aa' 'aah' 'aaniye' 'aaooooright' 'aathi' 'ab' 'abbey' 'abdomen' 'abeg'
 'abel']
